# Top of file
version: 2
jobs:
  build:
    macos:
      xcode: 11.3.0
    steps: # a series of commands to run
    - checkout  # pull down code from your version control system.
    - run:
        # build our application
        name: Build Application
        command: xcodebuild
